@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

title Carbon Awre API: CONTEXT DIAGRAM

System(jobrunr, "JobRunr", "A JobRunr BG Server that processes jobs")
System(intensityapi, "Carbon Intensity API", "The JobRunr Carbon Intensity API fetching carbon info")
System_Ext(entsoe, "ENTSO-E", "The default EU energy data provider")
System_Ext(dp2, "Data Provider 2", "Another energy data provider")

Rel_R(jobrunr, intensityapi, "Queries based on configured region")
Rel(intensityapi, entsoe, "Queries")
Rel(intensityapi, dp2, "Queries")

@enduml
