---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - push
    - pull_request

concurrency:
  limit: 1

steps:
  - name: prepare
    image: plugins/docker
    commands:
      - docker build -f PrepareDockerfile -t jobrunr.io/build-container:1.3 .
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  - name: build
    image: jobrunr.io/build-container:1.3
    commands:
      - rm -rf /tmp/reports/*
      - find /root/.gradle -name "*.lock" -type f -delete
      - find /drone/src/.gradle -name "*.lock" -type f -delete
      - ./gradlew -Djib.console=plain --no-daemon -i clean build test --fail-fast
      #- gradle assemble :tests:e2e-ui-gson:test :tests:e2e-ui-jackson:test  --tests org.jobrunr.tests.e2e.**
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: gradle-cache
        path: /root/.gradle
      - name: gradle-project-cache
        path: /drone/src/.gradle
      - name: frontend-node-modules-cache
        path: /drone/src/core/src/main/resources/org/jobrunr/dashboard/frontend/node_modules
      - name: frontend-build-cache
        path: /drone/src/core/src/main/resources/org/jobrunr/dashboard/frontend/build
      - name: maven-local
        path: /root/.m2
      - name: reports
        path: /tmp/reports

#  - name: slack
#    image: plugins/slack
#    settings:
#      webhook:
#        from_secret: SLACK_WEBHOOK
#      channel: drone
#    when:
#      status: [ success, failure ]

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: maven-local
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/m2/cache
  - name: gradle-cache
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/gradle/cache
  - name: gradle-project-cache
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/jobrunr/cache/gradle-project
  - name: frontend-node-modules-cache
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/jobrunr/cache/frontend-node-modules
  - name: frontend-build-cache
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/jobrunr/cache/frontend-build
  - name: reports
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/jobrunr/reports

---
kind: pipeline
type: docker
name: sonar

trigger:
  event:
    - custom

concurrency:
  limit: 1

steps:
  - name: prepare
    image: plugins/docker
    commands:
      - docker build -f PrepareDockerfile -t jobrunr.io/build-container:1.3 .
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  - name: build
    image: jobrunr.io/build-container:1.3
    commands:
      - rm -rf /tmp/reports/*
      - find /root/.gradle -name "*.lock" -type f -delete
      - find /drone/src/.gradle -name "*.lock" -type f -delete
      - ./gradlew --continue -Djib.console=plain --no-daemon -i clean build jacocoTestReport sonar
    environment:
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
      #- gradle assemble :tests:e2e-ui-gson:test :tests:e2e-ui-jackson:test  --tests org.jobrunr.tests.e2e.**
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: gradle-cache
        path: /root/.gradle
      - name: gradle-project-cache
        path: /drone/src/.gradle
      - name: frontend-node-modules-cache
        path: /drone/src/core/src/main/resources/org/jobrunr/dashboard/frontend/node_modules
      - name: frontend-build-cache
        path: /drone/src/core/src/main/resources/org/jobrunr/dashboard/frontend/build
      - name: maven-local
        path: /root/.m2
      - name: reports
        path: /tmp/reports

#  - name: slack
#    image: plugins/slack
#    settings:
#      webhook:
#        from_secret: SLACK_WEBHOOK
#      channel: drone
#    when:
#      status: [ success, failure ]

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: maven-local
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/m2/cache
  - name: gradle-cache
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/gradle/cache
  - name: gradle-project-cache
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/jobrunr/cache/gradle-project
  - name: frontend-node-modules-cache
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/jobrunr/cache/frontend-node-modules
  - name: frontend-build-cache
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/jobrunr/cache/frontend-build
  - name: reports
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/jobrunr/reports


---
kind: pipeline
type: docker
name: release

trigger:
  event:
    - tag

steps:
  - name: build-and-upload-to-maven-central
    image: jobrunr.io/build-container:1.3
    commands:
      - rm -f *.hprof
      - rm -rf /tmp/reports/*
      - find /root/.gradle -name "*.lock" -type f -delete
      - find /drone/src/.gradle -name "*.lock" -type f -delete
      - ./gradlew --no-daemon -i clean assemble publishToSonatype
    environment:
      SIGNING_KEY:
        from_secret: SIGNING_KEY
      SIGNING_PASSWORD:
        from_secret: SIGNING_PASSWORD
      ORG_GRADLE_PROJECT_sonatypeUsername:
        from_secret: ORG_GRADLE_PROJECT_sonatypeUsername
      ORG_GRADLE_PROJECT_sonatypePassword:
        from_secret: ORG_GRADLE_PROJECT_sonatypePassword
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: gradle-cache
        path: /root/.gradle
      - name: gradle-project-cache
        path: /drone/src/.gradle
      - name: frontend-node-modules-cache
        path: /drone/src/core/src/main/resources/org/jobrunr/dashboard/frontend/node_modules
      - name: frontend-build-cache
        path: /drone/src/core/src/main/resources/org/jobrunr/dashboard/frontend/build
      - name: maven-local
        path: /root/.m2
      - name: reports
        path: /tmp/reports

  #  - name: upload-to-github
  #    image: plugins/github-release
  #    settings:
  #      api_key:
  #        from_secret: GITHUB_TOKEN
  #      files: core/build/libs/*
  #    when:
  #      event: tag

  - name: update and push readme
    image: jobrunr.io/build-container:1.3
    environment:
      GITHUB_PAT:
        from_secret: GITHUB_TOKEN
    commands:
      - rm -f *.hprof
      - sed -i "s@<version>.*</version>@<version>${DRONE_TAG}</version>@g" README.md # replace version in README
      - sed -i "s@'org.jobrunr:jobrunr:.*'@'org.jobrunr:jobrunr:${DRONE_TAG}'@g" README.md # replace version in README
      - git config --global user.email "drone-bot@jobrunr.io"
      - git config --global user.name "drone-bot"
      - git add README.md
      - git commit -m "Update readme to version ${DRONE_TAG} [CI SKIP]"
      - git push https://$(GITHUB_PAT)@github.com/jobrunr/jobrunr.git

#  - name: slack
#    image: plugins/slack
#    settings:
#      webhook:
#        from_secret: SLACK_WEBHOOK
#      channel: drone
#    when:
#      status: [ success, failure ]

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: maven-local
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/m2/cache
  - name: gradle-cache
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/gradle/cache
  - name: gradle-project-cache
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/jobrunr/cache/gradle-project
  - name: frontend-node-modules-cache
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/jobrunr/cache/frontend-node-modules
  - name: frontend-build-cache
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/jobrunr/cache/frontend-build
  - name: reports
    host:
      path: /volume2/docker/jobrunr-services/drone-work-dir/jobrunr/reports

