name: Bug report
description: Create a bug report to help us improve JobRunr. 
title: "[BUG]"
body:
  - type: markdown
    attributes:
      value: |
        Lately we have been getting a lot of **invalid bug reports** (there was no bug) that take us a lot of time to investigate. This is time we cannot spend on improving JobRunr or the documentation. That's why we now have put in place the following **community guidelines**.
        
        ## Before creating a bug report
        ### Have a complete and up-to-date GitHub profile
        :wave: Hey, I'm [Ronald](https://github.com/rdehuyss), the creator and lead engineer of [JobRunr](https://www.jobrunr.io/). Nice to meet you! Who are you?
        <br />JobRunr is an open-source project where we try to make a living from, so we kindly ask you to have a **complete Github Personal Profile** (Name and Company details or LinkedIn Profile). It's always nice to know to whom we're talking to and providing free support to. If your Github Profile is not complete, we will probably close the issue without answering. For more info, read this excellent blog post about [open-source etiquette](https://www.yegor256.com/2020/07/29/open-source-etiquette.html).
        
        ### Don't post questions here!
        If you have a question, please review the [docs](https://www.jobrunr.io/en/documentation/) - they are really extensive. If you still can't find your answer there, then go to the discussions and ask there. Maintaining this takes a lot of time and discussions are sometines other people help there too which gives me time to improve JobRunr itself.
        
        ### Have a reproducible scenario
        Make sure that you have a reproducable scenario. We prefer Github repo's with exact steps in a `README.md` on how to launch the application and how to reproduce the bug you're having. If you do not take the time to create a reproducable scenario, why should we invest our **free time** in trying to figure out what happened? Reason for this is that I've seen people/organizations that adapted JobRunr source code, created bugs while doing so, used that in their own project and then created bug reports here. Not having a reproducable scenario will deem the issue invalid. 
        <br />If for some reason (confidential code, time, ...) you cannot a GitHub repo that reproduces the issue, feel free to get a [Pro subscription](https://www.jobrunr.io/en/pricing/) that comes with support.
        
        ## After creating the issue
        Pease make sure that the bug report is complete: title is not optional and code should be formatted. 
        You should also not assign me or somebody else to the issue. We're a self-organizing team and monitor the JobRunr issues. We also take holidays :palm_tree: from time to time and it may take us a couple of days to answer you.
        If you cannot wait that long, I also invite you to take a [Pro subscription](https://www.jobrunr.io/en/pricing/) that comes with better support.
        <br />Thank you for reading this far and do know that **we take this seriously - if you do too**.
        
        :clap: :pray: 
        
  - type: input
    id: version
    attributes:
      label: JobRunr Version
      description: What version of JobRunr are you running? If you are not running the latest version, we will probably close it without answering.
      placeholder: ex. 6.0.0
    validations:
      required: true
  - type: input
    id: jdk-version
    attributes:
      label: JDK Version
      description: Which JRE/JDK are you using?
      placeholder: ex. OpenJDK 1.8.0_292
    validations:
      required: true
  - type: input
    id: storage-provider
    attributes:
      label: Your SQL / NoSQL database
      description: Which database are you using?
      placeholder: ex. Postgres 9 / MongoDB 4.4
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce?
      description: Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo). If this is not provided, we will close your issue right away.
      placeholder: How can we reproduce the issue?
      value: >
         ```java
            BackgroundJob.enqueue(() -> service.helpMe());
         ```
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
#  - type: checkboxes
#    id: terms
#    attributes:
#      label: Code of Conduct
#      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
#      options:
#        - label: I agree to follow this project's Code of Conduct
#          required: true
