# Trigger on branch and event filters
when:
  - event:
      - push
      - pull_request
    branch:
      - master
      - v8
  - event: manual


workspace:
  path: jobrunr/src    # relative to base :contentReference[oaicite:1]{index=1}

steps:
  - name: prepare
    image: woodpeckerci/plugin-kaniko
    settings:
      dockerfile: PrepareDockerfile
      context: .
      repo: jobrunr.io/build-container
      tags: 1.4.1

  - name: build
    image: jobrunr.io/build-container:1.4.1
    commands:
      - rm -rf /tmp/reports/*
      - find /drone/jobrunr/src/.gradle -name "*.lock" -type f -delete
      - |
        bash -lc '
          set -e -o pipefail
          ./gradlew --no-daemon -Djib.console=plain --info clean build test --fail-fast \
            | grep -Ev "^(Found locally available resource with matching checksum|BuildToolsApiClasspathEntrySnapshotTransform|ClasspathEntrySnapshotTransform|Resource missing\\.)"
        '
    environment:
      BUILD_CACHE_USER:
        from_secret: BUILD_CACHE_USER
      BUILD_CACHE_PASSWORD:
        from_secret: BUILD_CACHE_PASSWORD  # secrets moved under environment/from_secret