when:
  event:
    - tag

steps:
  - name: prepare-docker-build-container
    image: docker
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "Running on ${CI_SYSTEM_NAME:-<not set>}"
      - docker build -f BuildDockerfile -t container-registry.jobrunr.io/build-container:latest .

  - name: build-and-upload-to-maven-central
    image: container-registry.jobrunr.io/build-container:latest
    commands:
      - rm -f *.hprof
      - rm -rf /tmp/reports/*
      - find /woodpecker/jobrunr/src/.gradle -name "*.lock" -type f -delete
      - |
        bash -lc '
          set -e -o pipefail
          gradle --no-daemon -Djib.console=plain --info clean assemble publishToSonatype nexusPushFromStagingToCentral \
            | grep -Ev "^(Found locally available resource with matching checksum|BuildToolsApiClasspathEntrySnapshotTransform|ClasspathEntrySnapshotTransform|Resource missing\\.)"
        '
    environment:
      BUILD_CACHE_USER:
        from_secret: BUILD_CACHE_USER
      BUILD_CACHE_PASSWORD:
        from_secret: BUILD_CACHE_PASSWORD
      SIGNING_KEY:
        from_secret: SIGNING_KEY
      SIGNING_PASSWORD:
        from_secret: SIGNING_PASSWORD
      SONATYPE_AUTH_HEADER:
        from_secret: SONATYPE_AUTH_HEADER
      ORG_GRADLE_PROJECT_sonatypeUsername:
        from_secret: ORG_GRADLE_PROJECT_sonatypeUsername
      ORG_GRADLE_PROJECT_sonatypePassword:
        from_secret: ORG_GRADLE_PROJECT_sonatypePassword
